#ifndef DEFS_H
#define DEFS_H

enum OutputType
{
    NO_OUTPUT,
    RAW_OUTPUT,
    FORMATTED_OUTPUT
};

enum SortType
{
    INIT_SEED_ASC,
    RATING_DESC,
    GAME_DIFFERENTIAL_DESC,
    SERIES_DIFFERENTIAL_DESC,
    BUCHHOLZ_SCORE_DESC,
    SPLIT_POINTS_DESC,
    TIEBREAKER_PLACEMENT_ASC,
    SPLIT_TOURNAMENTS_PLACEMENT_ASC
};

enum SixteenSystem
{
    SINGLE_ELIM16,
    DOUBLE_ELIM16,
    GROUPS16,
    SWISS_GAME_DIFFERENTIAL16,
    SWISS_BUCHHOLZ16,
    SWISS_TRUE_RATING16
};

enum EightSystem
{
    NOT_APPLICABLE8,
    SINGLE_ELIM8,
    AFL_FINAL_EIGHT
};

enum TiebreakerSystem
{
    SINGLE_ELIM_TB,
    INIT_SEED_TB
};

enum QualificationParameter
{
    POINTS_QUALIFICATION,
    AVG_PLACEMENT_QUALIFICATION
};

enum InterQualifierSeeding
{
    IQS_INIT_SEED,
    IQS_MOST_RECENT_TOURNAMENT_PLACEMENT,
    IQS_SPLIT_POINTS,
    IQS_AVG_PLACEMENT
};

#endif